
modLoader="javafml" #mandatory

loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All Right's Reserved"

[[mods]] #mandatory


modId="kenjiscombatforms"
version="1.4.0" #mandatory
displayName="Epic Fight: KenjisCombatForms"
authors="Kenji" #optional

[[mixins]]
config = "mixins.kenjiscombatforms.json"


description='''This mod is an addon to the Epic Fight Mod that adds brand-new overhauled mechanics and features related to hand-to-hand combat and abilities! -Kenji'''

[modproperties.kenjiscombatforms]
configuredBackground="minecraft:textures/block/cherry_leaves.png"

[[dependencies.kenjiscombatforms]] #optional
    # the modid of the dependency
    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[47,)" #mandatory

    ordering="NONE"

    side="BOTH"
# Here's another dependency
[[dependencies.kenjiscombatforms]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.kenjiscombatforms]]
modId="epicfight"
mandatory=true

versionRange="[20.7.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.kenjiscombatforms]]
modId="wom"
mandatory=true

versionRange="[20.1.7.40,)"
ordering="NONE"
side="BOTH"


#[features.kenjiscombatforms]
#openGLVersion="[3.2,)"